### ISSUE TITLE
@media panics if it's not at end of a style string

### ISSUE THREAD

**Issue by futursolo** [futursolo/stylist-rs#1]
The following style will not be parsed properly:

```css
@media screen and (max-width: 300px) {
    width: 100%;
}

.other-class {
    color: black;
}

```
