### ISSUE TITLE
Failed to parse css when using "at rules"

### ISSUE THREAD

**Issue by radu781** [futursolo/stylist-rs#116]
I am trying to use `@keyframes` and `@-webkit-keyframes` (https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) in a css file to create a spinning image effect but I get this runtime error: 

```text
Failed to Parse CSS, due to:
0: at line 112, in Many0:
@-webkit-keyframes rotating {
^
```

`component.rs` code:

```rust
use stylist::Style;
const STYLE_FILE: &str = include_str!("../../styles/component.css");
/* ... */
fn view(&self, ctx: &Context<Self>) -> Html {
    /* ... */
    let style_sheet = Style::new(STYLE_FILE).unwrap();
    html! {
    <div class={style_sheet}>
    /* ... */ 
}
```

`component.css` code:
``` css
@-webkit-keyframes rotating {
    to {
        /* ... */
        transform: rotate(0deg);
    }
    from {
        /* ... */
        transform: rotate(360deg);
    }
}

@keyframes rotating {
    to {
        /* ... */
        transform: rotate(0deg);
    }
    from {
        /* ... */
        transform: rotate(360deg);
    }
}

.spinner {
    /* ... */
    animation: rotating 2s linear infinite;
}
```

Is there a way I can workaround this issue or is this going to be fixed in the future?
