### ISSUE TITLE
Style leaking with selector list

### ISSUE THREAD

**Issue by futursolo** [futursolo/stylist-rs#20]
Currently stylist cannot handle selector list properly:

```css
div, span {
    color: red;
}
```

Will result in:
```css
.stylist-12345678 div, span {
    color: red;
}
```
