### ISSUE TITLE
(Inline) Descendant combinator is not recognised properly

### ISSUE THREAD

**Issue by futursolo** [futursolo/stylist-rs#41]
For the following stylesheet:
```css
.class-a.class-b {
    color: red;
}
.class-a .class-b {
    color: blue
}
```

For inline syntax, the input above yields the following stylesheet:
```css
.class-a.class-b {
    color: red;
}
.class-a.class-b {
    color: blue;
}
```

After consulting the documentation of `proc_macro2`, I am not sure what's the best course of action to solve this issue.
(I don't think possible to detect spaces between `Ident` and `Punct`.)

@WorldSEnder Any ideas?
